In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/citibike_weather_daily.csv")

In [4]:
df.dtypes

ride_date               str
num_rides             int64
avg_duration_min    float64
temp_f              float64
max_temp_f          float64
min_temp_f          float64
wind_speed_knots    float64
precip_in           float64
day_of_week             str
month                 int64
dtype: object

In [5]:
df["ride_date"] = pd.to_datetime(df["ride_date"])

In [6]:
df.dtypes

ride_date           datetime64[us]
num_rides                    int64
avg_duration_min           float64
temp_f                     float64
max_temp_f                 float64
min_temp_f                 float64
wind_speed_knots           float64
precip_in                  float64
day_of_week                    str
month                        int64
dtype: object

In [7]:
print("Temperature 9999.9:", (df["temp_f"] == 9999.9).sum())
print("Max temperature 9999.9:", (df["max_temp_f"] == 9999.9).sum())
print("Min temperature 9999.9:", (df["min_temp_f"] == 9999.9).sum())
print("Wind 999.9:", (df["wind_speed_knots"] == 999.9).sum())
print("Precipitation 99.99:", (df["precip_in"] == 99.99).sum())

Temperature 9999.9: 0
Max temperature 9999.9: 0
Min temperature 9999.9: 0
Wind 999.9: 0
Precipitation 99.99: 1

In [8]:
df[df["precip_in"] == 99.99]

,ride_date,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,day_of_week,month
951,2016-02-11,18748,13.523118,28.1,39.9,23.0,17.3,99.99,Thursday,2

In [9]:
df["precip_in"] = df["precip_in"].replace(99.99, np.nan)

In [10]:
df[df["ride_date"] == "2016-02-11"]["precip_in"]

951   NaN
Name: precip_in, dtype: float64

In [11]:
precip_median = df["precip_in"].median()

precip_median

np.float64(0.0)

In [12]:
df["precip_in"] = df["precip_in"].fillna(precip_median)

In [13]:
df["precip_in"].isna().sum()

np.int64(0)

In [14]:
df[df["ride_date"] == "2016-02-11"][["ride_date", "precip_in"]]

     ride_date  precip_in
951 2016-02-11        0.0

In [15]:
day_dummies = pd.get_dummies(
    df["day_of_week"],
    prefix="day",
    drop_first=True,
    dtype=int
)

day_dummies.head()

,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday
0,1,0,0,0,0,0
1,0,0,0,0,1,0
2,0,0,0,0,0,1
3,0,0,0,1,0,0
4,0,0,0,0,0,0

In [16]:
df = pd.concat([df, day_dummies], axis=1)

In [17]:
df = df.drop(columns=["day_of_week"])

In [18]:
df.shape

(1610, 15)

In [19]:
df["year"] = df["ride_date"].dt.year

In [20]:
df[["ride_date", "year"]].head()

   ride_date  year
0 2013-07-01  2013
1 2013-07-02  2013
2 2013-07-03  2013
3 2013-07-04  2013
4 2013-07-05  2013

In [21]:
df["temp_f_squared"] = df["temp_f"] ** 2

In [22]:
df[["temp_f", "temp_f_squared"]].head()

   temp_f  temp_f_squared
0    74.8         5595.04
1    76.1         5791.21
2    78.5         6162.25
3    82.0         6724.00
4    84.4         7123.36

### C5 — Squared Temperature Feature

I created a squared temperature feature because E3 showed that the relationship between temperature and ridership was not completely linear, especially on the hottest days. The squared temperature term allows the linear regression model to capture some curvature in the relationship between temperature and daily ridership.

In [23]:
df["temp_f_squared"] = df["temp_f"] ** 2

In [24]:
df[["temp_f", "temp_f_squared"]].head()

   temp_f  temp_f_squared
0    74.8         5595.04
1    76.1         5791.21
2    78.5         6162.25
3    82.0         6724.00
4    84.4         7123.36

### C5 — Squared Temperature Feature

I created a squared temperature feature because E3 showed that the relationship between temperature and ridership was not completely linear, especially on the hottest days. The squared temperature term allows the linear regression model to capture some curvature in the relationship between temperature and daily ridership.

In [25]:
df.columns

Index(['ride_date', 'num_rides', 'avg_duration_min', 'temp_f', 'max_temp_f',
       'min_temp_f', 'wind_speed_knots', 'precip_in', 'month', 'day_Monday',
       'day_Saturday', 'day_Sunday', 'day_Thursday', 'day_Tuesday',
       'day_Wednesday', 'year', 'temp_f_squared'],
      dtype='str')

In [26]:
df.to_csv("../data/citibike_weather_daily_clean.csv", index=False)

In [27]:
import os

os.path.exists("../data/citibike_weather_daily_clean.csv")

True

In [28]:
clean_df = pd.read_csv("../data/citibike_weather_daily_clean.csv")

clean_df.shape

(1610, 17)

In [29]:
clean_df.columns

Index(['ride_date', 'num_rides', 'avg_duration_min', 'temp_f', 'max_temp_f',
       'min_temp_f', 'wind_speed_knots', 'precip_in', 'month', 'day_Monday',
       'day_Saturday', 'day_Sunday', 'day_Thursday', 'day_Tuesday',
       'day_Wednesday', 'year', 'temp_f_squared'],
      dtype='str')

In [30]:
clean_df.to_csv("../data/citibike_weather_daily_clean.csv", index=False)

print("Clean dataset saved successfully.")

Clean dataset saved successfully.